[package]
name = "pax-chassis-macos"
edition = "2021"
version = "0.0.1"
authors = ["Zack Brown <zack@pax.rs>"]
license = "MIT OR Apache-2.0"
homepage = "https://www.pax.rs/"
repository = "https://www.github.com/pax-lang/pax"
description = "Platform-specific chassis allowing Pax cartridges to be executed as native macOS apps"


[build]
lto = true
incremental = false

[lib]
name = "paxchassismacos"
crate-type = ["cdylib"]

[dependencies]
piet = "0.6.0"
piet-coregraphics = "0.6.0"
pax-core = { path = "../../../../pax-core", version="0.0.1" }
pax-cartridge = { version="0.0.1"}
pax-message = {path = "../../../../pax-message", version="0.0.1"}
pax-runtime-api = {path = "../../../../pax-runtime-api", version="0.0.1"}
pax-properties-coproduct = { version="0.0.1"}
lazy_static = "1.4.0"
mut_static = "5.0.0"
core-graphics = "0.22.3"
serde = "1.0"
flexbuffers = "2.0.0"

[patch.crates-io]
pax-cartridge = { path = "../../cartridge" }
pax-properties-coproduct = { path = "../../properties-coproduct" }

#be cautious about core-graphics' version number --
#ideally this would be locked with `piet` (the specified version should exactly match the version used
#internally by piet-coregraphics, e.g. 0.6.0 => 0.22.3)


#[patch.'file:///Users/zack/code/pax-lang/pax-properties-coproduct']
#pax-properties-coproduct = {path = "../pax-cartridge/pax-properties-coproduct"}
#
#[patch.'file:///Users/zack/code/pax-lang/pax-cartridge']
#pax-cartridge = {path = "../pax-cartridge/pax-cartridge"}

#[patch.crates-io]
#pax-properties-coproduct = {path = "../pax-cartridge/pax-properties-coproduct"}
#pax-cartridge = {path = "../pax-cartridge/pax-cartridge"}