[package]
name = "pax-chassis-web"
version = "0.0.1"
authors = ["Zack Brown <zack@inclination.co>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
piet = "0.5.0"
piet-web = "0.5.0"


#pax-core is sufficient to break wasmpack.  try binary-removing its dependencies for trial & error?
pax-core = { path = "../pax-core" }
pax-properties-coproduct = {path = "../pax-properties-coproduct"}
pax-cartridge-runtime = {path = "../pax-cartridge-runtime"}
pax-runtime-api = {path = "../pax-runtime-api"}

wasm-bindgen = {version = "0.2.30", features=["serde-serialize"]}
#++serde = {version = "1.0", features=["derive"]}
#++serde-wasm-bindgen = "0.1.3"
console_error_panic_hook = { version = "0.1.6", optional = true }

[dependencies.web-sys]
version = "0.3.10"
features = ["console", "CanvasRenderingContext2d", "Window", "Document", "Element", "HtmlElement", "HtmlCanvasElement", "Event"]
