[package]
name = "pax"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pax-macro = {path="../pax-macro"}
pax-compiler = {path="../pax-compiler"}
pax-message = {path="../pax-message"}
pax-core = {path="../pax-core"}
pax-std = {path="../pax-std"}


[features]
parser = ["pax-std/parser"]