[workspace]

members = [
    "carbon",
    "carbon-chassis-web",
    "carbon-macro-expression",
]

default-members = [
    "carbon",
    "carbon-chassis-web",
    "carbon-macro-expression",
]


[profile.release]
lto = true
opt-level = 'z'