[workspace]

members = [
    "pax",
    "pax-core",
    "pax-chassis-web",
    "pax-macro-expression",
    "pax-compiler",
    "pax-dev-server",
]

default-members = [
    "pax",
    "pax-core",
    "pax-chassis-web",
    "pax-macro-expression",
    "pax-compiler",
    "pax-dev-server",
]


[profile.release]
lto = true
opt-level = 'z'