[workspace]

members = [
    "pax",
    "pax-core",
    "pax-chassis-web",
    "pax-macro",
    "pax-message",
    "pax-compiler",
    "pax-dev-server",
    "pax-properties-coproduct",
]

exclude = [
    "pax-example",
]


[profile.release]
lto = true
opt-level = 'z'


