[workspace]

members = [
    "carbon",
    "carbon-chassis-web",
    "carbon-macro-expression",
    "carbon-template-compiler",
    "carbon-metaruntime",
]

default-members = [
    "carbon",
    "carbon-chassis-web",
    "carbon-macro-expression",
    "carbon-template-compiler",
    "carbon-metaruntime",
]


[profile.release]
lto = true
opt-level = 'z'