[workspace]

members = [
    "pax-lang",
    "pax-core",
    "pax-chassis-web",
    "pax-chassis-macos",
    "pax-macro",
    "pax-message",
    "pax-compiler",
    "pax-properties-coproduct",
    "pax-runtime-api",

]

exclude = [
    "pax-example",
    "pax-std",
    "pax-chassis-macos/pax-dev-harness-macos",
    "pax-cartridge",
]


[profile.release]
lto = true
opt-level = 'z'


