[workspace]

members = [
    "pax",
    "pax-core",
    "pax-chassis-web",
    "pax-macro",
    "pax-message",
    "pax-compiler",
    "pax-properties-coproduct",
    "pax-runtime-api",
    "pax-cartridge-runtime",
]

exclude = [
    "pax-example",
    "pax-std",
    "pax-example/.pax-manual/patches/pax-cartridge-runtime",
    "pax-example/.pax-manual/patches/pax-properties-coproduct",
]


[profile.release]
lto = true
opt-level = 'z'


