[package]
name = "parser-bin-harness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pax-parser-bin = "0.0.0"

[patch]
pax-parser-bin = { path = "{{PARSER_BIN_PATH}}"}