[package]
name = "pax-chassis-macos"
edition = "2021"
version = "0.0.1"
authors = ["Zack Brown <zack@inclination.co>"]
description = "Pax chassis for macOS"
publish = false

[build]
lto = true
incremental = false

[lib]
name = "paxchassismacos"
crate-type = ["cdylib"]

[dependencies]
piet = "0.5.0"
piet-coregraphics = "0.5.0"
pax-core = { path = "../pax-core" }
pax-cartridge = {path = "../pax-cartridge"}
pax-message = {path = "../pax-message"}
pax-runtime-api = {path = "../pax-runtime-api"}
lazy_static = "1.4.0"
mut_static = "5.0.0"
core-graphics = "0.22.3"
#be cautious about core-graphics' version number --
#ideally this would be locked with `piet` (the specified version should exactly match the version used
#internally by piet-coregraphics, e.g. 0.5.0 => 0.22.3)

