[package]
name = "pax-runtime-api"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kurbo = "0.8.3"
lazy_static = "1.4.0"
mut_static = "5.0.0"
pax-macro = {path = "../pax-macro"}
uuid = {version = "0.8", features = ["v4", "wasm-bindgen"]}
pax-compiler = {path="../pax-compiler", optional = true}

[features]
parser = ["dep:pax-compiler"]