[package]
name = "pax-compiler"
version = "0.1.0"
authors = ["Zack Brown <zack@inclination.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#
#[lib]
#crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
pax-core = { path = "../pax-core" }
pest = "2.1.3"
pest_derive = "2.1.0"
lazy_static = "1.4.0"
clap = "2.33.3"
actix = "0.10"
actix-web = "3"
actix-files = "0.5.0"
actix-web-actors = "3"
rand = "0.8.4"

wasm-bindgen = {version = "0.2.30", features=["serde-serialize"]}
#++serde = {version = "1.0", features=["derive"]}
#++serde-wasm-bindgen = "0.1.3"
console_error_panic_hook = { version = "0.1.6", optional = true }

[dependencies.web-sys]
version = "0.3.10"
features = ["console", "CanvasRenderingContext2d", "Window", "Document", "Element", "HtmlElement", "HtmlCanvasElement", "Event"]
