[package]
name = "pax-compiler"
version = "0.0.1"
authors = ["Zack Brown <zack@inclination.co>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#
[lib]
name = "parser"
path = "src/parser.rs"


[features]
default = ["console_error_panic_hook", "cbor", "json", "messagepack"]
json = ["serde", "serde_json"]
messagepack = ["serde"]
cbor = ["serde"]

[dependencies]
pax-message = { path = "../pax-message" } 
pest = "2.1.3"
pest_derive = "2.1.0"
lazy_static = "1.4.0"
clap = "2.33.3"
actix = "0.10"
actix-web = "3"
actix-files = "0.5.0"
actix-web-actors = "3"
rand = "0.8.4"
tokio = { version = "1", features = ["full"] }
portpicker = "0.1.1"
tokio-serde = { version = "0.8.0", features = ["json"]}
serde = { version = "1", features=["derive"], optional = true }
serde_json = { version = "1.0", optional = true }
wasm-bindgen = {version = "0.2.30", features=["serde-serialize"]}
console_error_panic_hook = { version = "0.1.6", optional = true }
futures = "0.3"
tokio-stream = "0.1.8"
tokio-util = { version = "0.6", features = ["codec"] }
uuid = {version = "0.8", features = ["v4"] }
bincode = "1.3.3"



[dependencies.web-sys]
version = "0.3.10"
features = ["console", "CanvasRenderingContext2d", "Window", "Document", "Element", "HtmlElement", "HtmlCanvasElement", "Event"]


