[package]
name = "pax-std-primitives"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pax = {package="pax-lang", path = "../pax-lang"}
pax-core = {path = "../../pax-core"}
pax-std = {path = "../"}
pax-runtime-api = {path = "../../pax-runtime-api"}
pax-message = {path = "../../pax-message" }
pax-properties-coproduct = {path = "../../pax-properties-coproduct"}
piet = "0.5.0"
piet-common = "0.5.0"
kurbo = "0.8.3"