[package]
name = "pax-std-primitives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pax-core = {path = "../../pax-core"}
pax-std = {path = "../"}
pax-runtime-api = {path = "../../pax-runtime-api"}
piet = "0.3.1"
piet-web = "0.3.1"
kurbo = "0.7.1"