[package]
name = "pax-expression-table"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#pax-example = { path = "../../.." }
pax-core = { path = "../../../../pax-core" }
pax-properties-coproduct = { path = "../pax-properties-coproduct" }