[package]
name = "pax-cartridge"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piet-common = "0.5.0"
pax-core = {path = "../pax-core"}
pax-example = {path = "../pax-example"}
pax-std-primitives = {path = "../pax-std/pax-std-primitives"}
pax-runtime-api = {path = "../pax-runtime-api"}
pax-properties-coproduct = {path="../pax-properties-coproduct"}

[patch.'file://../pax-properties-coproduct']
pax-properties-coproduct = {path = "./pax-properties-coproduct"}