[package]
name = "pax-cartridge"
version = "0.0.1"
authors = ["Zack Brown <zack@pax-lang.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://www.pax-lang.org/"
repository = "https://www.github.com/pax-lang/pax"
description = "Static program definition container for Pax programs, intended to be patched during compilation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piet-common = "0.5.0"
pax-core = {path = "../pax-core", version = "0.0.1"}
#pax-example = {path = "../pax-example"}
pax-runtime-api = {path = "../pax-runtime-api", version = "0.0.1"}
#pax-properties-coproduct = {path="../pax-properties-coproduct"}

#[patch.'file:///Users/zack/code/pax-lang/pax-properties-coproduct']
#pax-properties-coproduct = {path = "./pax-properties-coproduct"}