[package]
name = "pax-example"
version = "0.0.1"
authors = ["Zack Brown <zack@pax-lang.org>"]
edition = "2021"

[dependencies]
pax = {package="pax-lang", path = "../pax-lang"}
pax-std = {path = "../pax-std"}

