[package]
name = "pax-example"
version = "0.1.0"
authors = ["Zack Brown <zack@inclination.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


#TODO: delete this section once lib.rs is expanded by macro
[lib]
name="pax_example"
path = "src/lib-expanded.rs"

### GENERATE
[[bin]]
name = "parser"
path = "src/lib-expanded.rs"
required-features = ["parser"]
### END GENERATE

[features]
### GENERATE
parser = ["pax-std/parser"]
### END GENERATE

[dependencies]
pax = {path = "../pax"}
pax-std = {path = "../pax-std"}
### REMOVE once lazy_static pascal_identifier hack is removed from manually expanded prototype macros
lazy_static = "*"



