[package]
name = "pax-example"
version = "0.1.0"
authors = ["Zack Brown <zack@inclination.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


### GENERATE
[[bin]]
name = "parser"
path = "src/lib-expanded.rs"
required-features = ["parser"]
### END GENERATE

[features]
### GENERATE
parser = []
### END GENERATE

[dependencies]
pax = { path = "../pax" }
lazy_static = "*"

