[package]
name = "pax-example"
version = "0.1.0"
authors = ["Zack Brown <zack@inclination.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


### GENERATE
[[bin]]
name = "derive-manifest"
path = "src/lib-expanded.rs"
required-features = ["derive-manifest"]
### END GENERATE

[features]
### GENERATE
derive-manifest = []
### END GENERATE

[dependencies]
pax = { path = "../pax" }
lazy_static = "*"

