
[package]
name = "pax-std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[package.metadata.pax]
primitives_crate = "./pax-std-primitives"

[dependencies]
piet = "0.3.1"
kurbo = "0.7.1"
pax = {path = "../pax"}
lazy_static = "*"

[features]
parser = []