
[package]
name = "pax-std"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[package.metadata.pax]
primitives_crate = "./pax-std-primitives"

[dependencies]
piet = "0.5.0"
kurbo = "0.8.3"
pax = {package="pax-lang", path = "../pax-lang", features = ["parser"]}
pax-message = {path = "../pax-message"}
lazy_static = "*"
pax-compiler = {path="../pax-compiler", optional = true}
serde_json = {version="1", optional = true}

[features]
parser = ["dep:pax-compiler", "dep:serde_json"]