[package]
name = "pax-core"
version = "0.1.0"
authors = ["Zack Brown <zack@inclination.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piet = "0.3.1"
piet-web = "0.3.1"
kurbo = "0.7.1"
pax-macro = { path = "../pax-macro"}
pax-properties-coproduct = { path = "../pax-example/.pax-manual/patches/pax-properties-coproduct"}
lazy_static = "1.4.0"
wasm-bindgen = {version = "0.2.30", features=["serde-serialize"]}
serde = {version = "1.0", features=["derive"]}
serde-wasm-bindgen = "0.1.3"


[features]
designtime = []


[target.'cfg(target_arch="wasm32")'.dependencies]
piet-web = "0.3.1"
wasm-bindgen = { version = "0.2.59", features = ["serde-serialize"] }

#
#[patch.'file://../pax-properties-coproduct']
#pax-properties-coproduct = { path = "../pax-example/.pax-manual/patches/pax-properties-coproduct"}
