[package]
name = "pax-cli"
version = "0.1.0"
authors = ["Zack Brown <zack@pax-lang.org>"]
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://www.pax-lang.org/"
repository = "https://www.github.com/pax-lang/pax"
description = "Command line interface tool for developing, packaging, and managing Pax projects"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-serde = { version = "0.8.0", features = ["json"]}
tokio-stream = "0.1.8"
tokio-util = { version = "0.6", features = ["codec"] }
clap = "2.33.3"
pax-compiler = {path = "../pax-compiler", version = "0.0.1"}
